# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/semantic_retrieval',
                'doc_host': 'https://charlesvardeman.github.io',
                'git_url': 'https://github.com/charlesvardeman/semantic_retrieval',
                'lib_path': 'semantic_retrieval'},
  'syms': {'semantic_retrieval.core': {'semantic_retrieval.core.foo': ('core.html#foo', 'semantic_retrieval/core.py')}}}